/**
 * Fix import paths in all batch-generated client files
 * Components are at project root /components/, not inside /app/
 * Routes like app/break-even-calculator/business/[business]/ need ../../../../
 * 
 * node fix_import_paths.js
 */

const fs   = require('fs')
const path = require('path')

// All client files generated by build_500_more.js that have wrong paths
const clientFiles = [
  'app/break-even-calculator/business/[business]/BreakEvenClient.js',
  'app/car-loan-calculator/price/[price]/CarLoanPriceClient.js',
  'app/credit-card-payoff-calculator/balance/[balance]/CCPayoffClient.js',
  'app/freelance-rate-calculator/job/[job]/FreelanceRateClient.js',
  'app/inflation-calculator/year/[year]/InflationYearClient.js',
  'app/mortgage-calculator/price/[price]/MortgagePriceClient.js',
  'app/rent-vs-buy-calculator/city/[city]/RvBCityClient.js',
  'app/student-loan-calculator/amount/[amount]/StudentLoanClient.js',
  'app/401k-calculator/salary/[salary]/FourOhOneKClient.js',
  // Also fix data imports in page.js files for these routes
]

// Also fix page.js files that import from wrong data path
const pageFiles = [
  'app/break-even-calculator/business/[business]/page.js',
  'app/car-loan-calculator/price/[price]/page.js',
  'app/credit-card-payoff-calculator/balance/[balance]/page.js',
  'app/freelance-rate-calculator/job/[job]/page.js',
  'app/inflation-calculator/year/[year]/page.js',
  'app/mortgage-calculator/price/[price]/page.js',
  'app/rent-vs-buy-calculator/city/[city]/page.js',
  'app/student-loan-calculator/amount/[amount]/page.js',
  'app/401k-calculator/salary/[salary]/page.js',
  'app/break-even-calculator/business/[business]/layout.js',
  'app/car-loan-calculator/price/[price]/layout.js',
  'app/credit-card-payoff-calculator/balance/[balance]/layout.js',
  'app/freelance-rate-calculator/job/[job]/layout.js',
  'app/inflation-calculator/year/[year]/layout.js',
  'app/mortgage-calculator/price/[price]/layout.js',
  'app/rent-vs-buy-calculator/city/[city]/layout.js',
  'app/student-loan-calculator/amount/[amount]/layout.js',
  'app/401k-calculator/salary/[salary]/layout.js',
]

let fixed = 0
let notFound = 0

const allFiles = [...clientFiles, ...pageFiles]

for (const filePath of allFiles) {
  if (!fs.existsSync(filePath)) {
    console.log('⚠️  Not found: ' + filePath)
    notFound++
    continue
  }

  let content = fs.readFileSync(filePath, 'utf8')
  const original = content

  // Fix Header/Footer imports: ../../../components/ → ../../../../components/
  content = content.replace(/['"]\.\.\/\.\.\/\.\.\/components\/(Header|Footer)['"]/g, "'../../../../components/$1'")

  // Fix data imports in page.js/layout.js: ../../../data/ → ../../../../data/
  content = content.replace(/['"]\.\.\/\.\.\/\.\.\/data\//g, "'../../../../data/")

  // Also fix if they used the rel variable wrong and got ../../.. instead of ../../../..
  // (same pattern, already handled above)

  if (content !== original) {
    fs.writeFileSync(filePath, content, 'utf8')
    console.log('✅ Fixed: ' + filePath)
    fixed++
  } else {
    console.log('✓  OK (no change): ' + filePath)
  }
}

// Also check the salary-after-tax fix
const satClient = 'app/salary-after-tax/state/[state]/SATStateClient.js'
const satLayout = 'app/salary-after-tax/state/[state]/layout.js'
const satPage   = 'app/salary-after-tax/state/[state]/page.js'

for (const f of [satClient, satLayout, satPage]) {
  if (!fs.existsSync(f)) { console.log('⚠️  Not found: ' + f); notFound++; continue }
  let content = fs.readFileSync(f, 'utf8')
  const original = content
  content = content.replace(/['"]\.\.\/\.\.\/\.\.\/components\/(Header|Footer)['"]/g, "'../../../../components/$1'")
  content = content.replace(/['"]\.\.\/\.\.\/\.\.\/data\//g, "'../../../../data/")
  if (content !== original) { fs.writeFileSync(f, content, 'utf8'); console.log('✅ Fixed: ' + f); fixed++ }
  else console.log('✓  OK: ' + f)
}

console.log(`
Summary: ${fixed} files fixed, ${notFound} not found.

Now run:
  git add -A
  git commit -m "fix: correct import paths in batch-generated client files"
  vercel --prod
`)
