export default function sitemap() {
  const base = 'https://freefincalc.net'

  // ── Static pages ─────────────────────────────────────────────
  const staticPages = [
    { route: '',               priority: 1.0,  freq: 'daily'   },
    { route: 'blog',           priority: 0.8,  freq: 'daily'   },
    { route: 'about',          priority: 0.5,  freq: 'monthly' },
    { route: 'contact',        priority: 0.5,  freq: 'monthly' },
    { route: 'privacy-policy', priority: 0.3,  freq: 'monthly' },
    { route: 'terms',          priority: 0.3,  freq: 'monthly' },
  ]

  // ── Blog posts (41) ──────────────────────────────────────────
  const blogSlugs = [
    'bond-calculator-south-africa-2026',
    'debt-snowball-vs-avalanche',
    'home-loan-calculator-pakistan-2026',
    'home-loan-emi-calculator-india',
    'how-car-loans-work',
    'how-does-inflation-affect-savings',
    'how-inflation-works',
    'how-much-house-can-i-afford',
    'how-much-to-save-for-retirement',
    'how-personal-loans-work',
    'how-student-loans-work',
    'how-to-budget-50-30-20',
    'how-to-build-emergency-fund',
    'how-to-build-wealth',
    'how-to-calculate-loan-payment',
    'how-to-calculate-mortgage-payment',
    'how-to-calculate-net-worth',
    'how-to-create-monthly-budget',
    'how-to-get-out-of-debt',
    'how-to-invest-for-beginners',
    'how-to-lower-tax-bill',
    'how-to-max-out-roth-ira',
    'how-to-negotiate-salary',
    'how-to-pay-off-debt-fast',
    'how-to-read-pay-stub',
    'how-to-refinance-mortgage',
    'how-to-save-money-fast',
    'income-tax-calculator-india-2026',
    'isa-savings-calculator-uk',
    'loan-calculator-nigeria-2026',
    'mortgage-calculator-australia-2026',
    'mortgage-calculator-canada-2026',
    'mortgage-calculator-singapore-2026',
    'mortgage-calculator-uae-dubai-2026',
    'mortgage-calculator-uk-2026',
    'rent-vs-buy-home',
    'types-of-retirement-accounts',
    'what-is-a-good-credit-score',
    'what-is-an-emergency-fund',
    'what-is-compound-interest',
    'what-is-net-worth',
    'what-is-passive-income',
  ]

  // ── Calculators (103) ────────────────────────────────────────
  const calculators = [
    // Stage 2 (25)
    'mortgage-calculator',
    'amortization-calculator',
    'student-loan-calculator',
    'refinance-calculator',
    'debt-to-income-calculator',
    'home-affordability-calculator',
    'heloc-calculator',
    'property-tax-calculator',
    'rent-vs-buy-calculator',
    'emergency-fund-calculator',
    '401k-calculator',
    'roth-ira-calculator',
    'dividend-calculator',
    'stock-profit-calculator',
    'simple-interest-calculator',
    'apr-calculator',
    'interest-rate-calculator',
    'paycheck-calculator',
    'raise-calculator',
    'tip-calculator',
    'sales-tax-calculator',
    'vat-calculator',
    'currency-converter',
    'payoff-vs-invest-calculator',
    'net-worth-calculator',
    // Stage 3 (10)
    'payroll-tax-calculator',
    'bond-yield-calculator',
    'car-depreciation-calculator',
    'home-equity-calculator',
    'inflation-impact-calculator',
    'profit-margin-calculator',
    'break-even-calculator',
    'roi-calculator',
    'freelance-rate-calculator',
    'business-valuation-calculator',
    // Stage 4 (10)
    'hourly-to-salary-calculator',
    'salary-after-tax-calculator',
    'overtime-calculator',
    'cost-of-living-calculator',
    'moving-cost-calculator',
    'lease-vs-buy-calculator',
    'car-loan-calculator',
    'fuel-cost-calculator',
    'down-payment-calculator',
    'mortgage-points-calculator',
    // Stage 5 (10)
    'retirement-calculator',
    'social-security-calculator',
    'rmd-calculator',
    'investment-return-calculator',
    'portfolio-rebalancing-calculator',
    'dollar-cost-averaging-calculator',
    'personal-loan-calculator',
    'credit-card-payoff-calculator',
    'savings-interest-calculator',
    'net-investment-fee-calculator',
    // Stage 6 (10)
    'budget-planner-calculator',
    'rent-affordability-calculator',
    'net-pay-calculator',
    'tax-refund-calculator',
    'child-tax-credit-calculator',
    'estate-tax-calculator',
    'gift-tax-calculator',
    'rental-property-calculator',
    'cap-rate-calculator',
    'house-flipping-calculator',
    // Stage 7 (10)
    'business-loan-calculator',
    'sba-loan-calculator',
    'accounts-receivable-calculator',
    'cash-flow-calculator',
    'working-capital-calculator',
    'debt-service-coverage-calculator',
    'employee-cost-calculator',
    'startup-cost-calculator',
    'ecommerce-profit-calculator',
    'saas-metrics-calculator',
    // Stage 8 (5)
    'wedding-budget-calculator',
    'vacation-budget-calculator',
    'baby-cost-calculator',
    'pet-cost-calculator',
    'home-buying-cost-calculator',
    // Stage 9a (12)
    'debt-payoff-calculator',
    'tax-calculator',
    'capital-gains-tax-calculator',
    'self-employment-tax-calculator',
    'pension-calculator',
    'annuity-calculator',
    'life-insurance-calculator',
    'college-savings-calculator',
    'car-affordability-calculator',
    'home-improvement-loan-calculator',
    'solar-payback-calculator',
    'invoice-calculator',
    // Stage 9b (11)
    'markup-calculator',
    'discount-calculator',
    'loan-comparison-calculator',
    'biweekly-mortgage-calculator',
    'extra-payment-calculator',
    'cd-calculator',
    'savings-goal-calculator',
    'fire-calculator',
    'debt-consolidation-calculator',
    'balance-transfer-calculator',
    'insurance-calculator',

    // Stage 10 (21) — linked from homepage
    'boat-loan-calculator',
    'commission-calculator',
    'contractor-pay-calculator',
    'credit-card-minimum-payment-calculator',
    'credit-utilization-calculator',
    'debt-avalanche-calculator',
    'debt-payoff-time-calculator',
    'debt-snowball-calculator',
    'equipment-loan-calculator',
    'fire-retirement-calculator',
    'loan-interest-calculator',
    'loan-payment-calculator',
    'overtime-pay-calculator',
    'passive-income-calculator',
    'portfolio-growth-calculator',
    'retirement-savings-calculator',
    'rv-loan-calculator',
    'salary-to-hourly-calculator',
    'savings-growth-calculator',
    'total-debt-calculator',
    'truck-loan-calculator',
  ]

  const staticEntries = staticPages.map(p => ({
    url: p.route ? `${base}/${p.route}` : base,
    lastModified: new Date(),
    changeFrequency: p.freq,
    priority: p.priority,
  }))

  const blogEntries = blogSlugs.map(slug => ({
    url: `${base}/blog/${slug}`,
    lastModified: new Date(),
    changeFrequency: 'monthly',
    priority: 0.7,
  }))

  const calcEntries = calculators.map(route => ({
    url: `${base}/${route}`,
    lastModified: new Date(),
    changeFrequency: 'weekly',
    priority: 0.8,
  }))

  return [...staticEntries, ...blogEntries, ...calcEntries]
}
