import Header from '../../components/Header'
import Footer from '../../components/Footer'
import SchemaMarkup from '../components/SchemaMarkup';


export const metadata = {
  title: 'Terms of Service | FreeFinCalc',
  description: 'Terms of Service for FreeFinCalc.net — free financial calculators. Read our terms before using our site.',
  alternates: { canonical: 'https://freefincalc.net/terms' },
}

export default function TermsOfService() {
  return (
    <>
      <Header />
      <SchemaMarkup breadcrumbs={[{"name":"Home","url":"https://freefincalc.net/"},{"name":"Terms","url":"https://freefincalc.net/terms"}]} includeReview={true} />
      <main className="max-w-3xl mx-auto px-4 py-16">
        <h1 className="text-4xl font-bold text-white mb-2">Terms of Service</h1>
        <p className="text-slate-500 text-sm mb-10">Last updated: March 2026</p>

        <div className="space-y-8 text-slate-400 leading-relaxed">

          <section>
            <h2 className="text-xl font-bold text-white mb-3">1. Acceptance of Terms</h2>
            <p>By accessing and using FreeFinCalc.net (the "Site"), you accept and agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use the Site.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">2. Educational Use Only</h2>
            <p>All calculators and tools on FreeFinCalc.net are provided for <strong className="text-white">educational and informational purposes only</strong>. The results generated by our calculators are estimates and should not be considered financial, tax, legal, or investment advice.</p>
            <p className="mt-3">Always consult a qualified financial advisor, tax professional, or attorney before making financial decisions. Results may vary based on individual circumstances not captured by our calculators.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">3. No Warranties</h2>
            <p>FreeFinCalc.net provides all tools and content "as is" without warranty of any kind, express or implied. We do not warrant that:</p>
            <ul className="list-disc ml-6 mt-2 space-y-1">
              <li>Calculator results are accurate, complete, or current</li>
              <li>The Site will be uninterrupted or error-free</li>
              <li>Results are suitable for any particular purpose</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">4. Limitation of Liability</h2>
            <p>FreeFinCalc.net and its operators shall not be liable for any direct, indirect, incidental, special, or consequential damages resulting from your use of the Site or reliance on any calculator results. Your use of the Site is at your sole risk.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">5. Intellectual Property</h2>
            <p>All content on FreeFinCalc.net, including calculator logic, design, text, and code, is the property of FreeFinCalc and is protected by applicable copyright and intellectual property laws. You may not reproduce, distribute, or create derivative works without explicit written permission.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">6. Privacy</h2>
            <p>Your use of the Site is also governed by our <a href="/privacy-policy" className="text-yellow-400 hover:underline">Privacy Policy</a>. FreeFinCalc does not store or transmit any financial data you enter into our calculators. All calculations are performed locally in your browser.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">7. Third-Party Links</h2>
            <p>The Site may contain links to third-party websites. These links are provided for convenience only. FreeFinCalc has no control over and assumes no responsibility for the content, privacy policies, or practices of any third-party sites.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">8. Advertising</h2>
            <p>FreeFinCalc.net may display advertisements served by third-party ad networks including Google AdSense. These advertisers may use cookies to serve relevant ads. FreeFinCalc does not endorse any advertised products or services.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">9. Changes to Terms</h2>
            <p>FreeFinCalc reserves the right to modify these Terms at any time. Changes take effect immediately upon posting. Continued use of the Site constitutes acceptance of the revised Terms.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">10. Contact</h2>
            <p>If you have questions about these Terms, please contact us via our <a href="/contact" className="text-yellow-400 hover:underline">Contact page</a>.</p>
          </section>

        </div>
      </main>
      <Footer />
    </>
  )
}
